### ISSUE TITLE
Resizing window does not resize graph canvas

### ISSUE THREAD

**Issue by carlsc2** [smiled0g/knowledge-explorer#4]
The graph does not resize when I maximize the window, so I can only ever see a small portion of it. I'm running this on Windows 10. See image below:

![image](https://cloud.githubusercontent.com/assets/8629347/13377639/202e63e6-ddb1-11e5-9cff-ffca57962957.png)

**Comment by njbbaer** [comment]
A workaround is to add a new node, which resets the display size. However this should be eventually fixed.

**Comment by smiled0g** [comment]
A fix is pushed to https://github.com/smiled0g/knowledge-explorer/commit/fa25a417cb3fa30c0b30596047e1e55934f26652

Please verify that the problem is gone.

**Comment by smiled0g** [comment]
@carlsc2
